Repository milindra22/AddWord, pull requests merged in 2020-10, with the labels that each got.

#4 adding meaning full information in README.md for issue #1
  README.md
Labels: documentation, hacktoberfest-accepted

#5 added word file with initial information #2
  Word
Labels: documentation, hacktoberfest-accepted

#6 ache word is added in Word file. issue #3
  Word
Labels: documentation, hacktoberfest-accepted

#7 acquit word is added in word file. #3
  Word
Labels: documentation, hacktoberfest-accepted

#8 actor word is added in word file. #3
  Word
Labels: documentation, hacktoberfest-accepted

#9 vocabulary
  Word
Labels: documentation, hacktoberfest-accepted

#10 appetizer
  Word
Labels: documentation, hacktoberfest-accepted

#11 aroma
  Word
Labels: documentation, enhancement, hacktoberfest-accepted

#12 bake
  Word
Labels: documentation, hacktoberfest-accepted

#13 Update Word
  Word
Labels: enhancement, hacktoberfest-accepted

#14 Update Word
  Word
Labels: documentation, enhancement, hacktoberfest-accepted

#15 Update Word
  Word
Labels: documentation, enhancement, hacktoberfest-accepted

#16 Update Word
  Word
Labels: documentation, enhancement, hacktoberfest-accepted

#17 Update Word
  Word
Labels: documentation, enhancement, hacktoberfest-accepted

#18 Added malarkey and truculent.
  Word
Labels: enhancement, good first issue, hacktoberfest-accepted
